app:
  jwt:
    jwtExpirationMs: 86400000
    jwtSecret: mskSprtkSecretKey
server:
  port: 8097
spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost/authentication
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer